spring.profiles.active=local

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

# Logging
logging.level.com.epam=DEBUG
logging.level.org.springframework.web=INFO

initial.data.path=initial-data.properties