package com.epam.service.entity;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

// TODO:
//  For these points below please check all entities in the project, not just User
//  1. @Data produces @ToString with all fields included which leads to password being printed which is not secure
//  Consider using @Getter and @Setter instead
//  2. @Data produces @EqualsAndHashCode with all fields included which can lead to issues with JPA entities:
//  bad with mutable fields + can trigger lazy loads + can break Sets/Maps when fields change
//  (you can find what was generated by lombok at /target/classes once you've compiled the code)
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
@Entity
@Table(name = "users")
@Inheritance(strategy = InheritanceType.JOINED)
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String firstName;
    @Column(nullable = false)
    private String lastName;
    @Column(nullable = false, unique = true)
    private String username;
    @Column(nullable = false)
    private String password;
    private boolean isActive = true;

}